### ISSUE TITLE
Just Sharing: Software Engineering Practices at Google

### ISSUE THREAD

**Issue by robatron** [rei/code-style-guides#14]
Hello, not sure where best to share this, but I ran across this paper on software engineering at Google, and thought y'all might find it useful with respect to engineering practices, e.g., code style guides:

https://arxiv.org/abs/1702.01715

**Comment by NEWeber** [comment]
Thanks for sending us this @robatron!

**Comment by NEWeber** [comment]
Shared this with the team, closing.
